Repository TBD54566975/dwn-sdk-js, pull requests merged in 2023-10, with the labels that each got.

#528 remove use of dataStream for ProtocolsConfigure in tests
  README.md
  tests/handlers/protocols-configure.spec.ts
  tests/handlers/protocols-query.spec.ts
  tests/handlers/records-read.spec.ts
  tests/handlers/records-write.spec.ts
Labels: hacktoberfest-accepted

#527 #526 - Fix typos in the README.md file
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#532 Normalize schema and protocol in create method of permission-grant
  README.md
  src/interfaces/permissions-grant.ts
  tests/interfaces/permissions-grant.spec.ts
Labels: hacktoberfest, hacktoberfest-accepted

#583 adding helper function to create a timestamp
  src/index.ts
  src/utils/time.ts
  tests/utils/test-data-generator.ts
  tests/utils/time.spec.ts
Labels: hacktoberfest, hacktoberfest-accepted
