Repository TBD54566975/dwn-sdk-js, pull requests merged in 2024-10, with the labels that each got.

#820 Auth when reading deleted records
  CONTRIBUTING.md
  package.json
  src/core/dwn-error.ts
  src/handlers/records-read.ts
  tests/handlers/records-read.spec.ts
Labels: hacktoberfest, hacktoberfest-accepted, medium

#826 Fixes typos for Code of Conduct in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted, small

#825 update: Fixed all the typo errors
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted, small

#822 Explicitly export types not referenced by exported types
  package-lock.json
  package.json
  src/event-log/event-log-level.ts
  src/index.ts
  src/store/blockstore-level.ts
  src/store/data-store-level.ts
  src/store/index-level.ts
  src/store/level-wrapper.ts
  src/store/message-store-level.ts
  src/store/resumable-task-store-level.ts
  src/types/message-types.ts
Labels: hacktoberfest
